### ISSUE TITLE
Разработать текстовое представление письма

### ISSUE THREAD

**Issue by Andrew-By** [Andrew-By/OneMorePost#26]
Итак, благодаря общим усилиям, программа работает. Настало время "красивостей".

* Формат поста в группе
* Форма регистрации в нашем сервисе

Рассмотрим эти вопросы поподробнее:

## Формат поста в группе

Сообщение имеет сложную структуру:

* Ид
* Отправитель
* Тема
* Тело сообщения
* Дата получения
* Вложения

При этом, на сколько мне известно, в ВКонтакте пост является просто текстом (поправьте меня, если это не так). Таким образом, надо договориться о формате. Конечно, разумно дать пользователю возможность самому формат, но это мы оставим на потом - сейчас хватит и жёстко заданной структуры. Мой вариант такой:

От: [Отправитель]
Тема : [Тема]

[Тело сообщения]

**Comment by Andrew-By** [comment]
Да, и формат для Telegram тоже нужно обсудить

**Comment by stelsd** [comment]
Нормальный вариант, думаю нет смысла придумывать что-то другое

**Comment by Andrew-By** [comment]
Дело в том, что в таком варианте не учитывается дата/время когда пришло письмо

**Comment by stelsd** [comment]
так у нас же пост размещается почти сразу, поэтому время прихода думаю можно не писать и принять его как время размещения поста.

**Comment by Andrew-By** [comment]
Насчёт сразу - не уверен. Проверка почты происходит по расписанию. Сейчас, конечно, можно поставить 5 минут, но потом, когда пользователей будет много, думаю придётся сделать раз в 15 минут

**Comment by stelsd** [comment]
все равно мне кажется время прихода письма будет лишней информацией

**Comment by Andrew-By** [comment]
Хорошо

**Comment by Andrew-By** [comment]
Ещё такой вопрос. При отправке вложений на ВК возможно возникновение разного рода исключений. При этом всё-равно остаётся возможность сделать пост. Может, стоит тогда в него включать сообщение об ошибке?

## Пример ##

От: [Отправитель]
Тема : [Тема]

[Тело сообщения]

Сообщение содержало вложения, загрузка которых не удалась.
Exception trace...
